Repository kubernetes-sigs/container-object-storage-interface-controller, pull requests merged in 2020-10, with the labels that each got.

#2 adds issue templates to the COSI controller
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3 Add release tools
  release-tools/.prow.sh
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/code-of-conduct.md
  release-tools/filter-junit.go
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/update-vendor.sh
  release-tools/util.sh
  release-tools/verify-go-version.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
  release-tools/verify-vendor.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5 We maintain release tools only under Spec repo
  Dockerfile
  Makefile
  release-tools/.prow.sh
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/code-of-conduct.md
  release-tools/filter-junit.go
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/util.sh
  release-tools/verify-go-version.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
  release-tools/verify-vendor.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4 Add approvers to facilitate project management
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
