Repository kubernetes-sigs/container-object-storage-interface-controller, pull requests merged in 2020-12, with the labels that each got.

#7 Adding bucketrequest controller (WIP)
  .gitignore
  .prow.sh
  Makefile
  cmd/controller-manager/controller-manager.go
  go.mod
  go.sum
  pkg/bucketrequest/bucketrequest.go
  pkg/bucketrequest/bucketrequest_test.go
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#16 Fix kubeconfig flag
  cmd/controller-manager/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#18 Added Kustomize for controller, sidecar & CRDs
  deploy/base/deployment.yaml
  deploy/base/ns.yaml
  deploy/base/rbac.yaml
  deploy/base/sa.yaml
  kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#15 Adding BucketAccess Add Functionality, Fix cmd controller and pass co…
  cmd/controller-manager/controller-manager.go
  go.mod
  go.sum
  pkg/bucketaccessrequest/bucketaccessrequest.go
  pkg/bucketaccessrequest/bucketaccessrequest_test.go
  pkg/bucketrequest/bucketrequest.go
  pkg/bucketrequest/bucketrequest_test.go
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#26 Refactor Kustomize deployment
  deploy/base/deployment.yaml
  deploy/base/kustomization.yaml
  deploy/base/rbac.yaml
  deploy/base/sa.yaml
  deploy/fullstack/controller/kustomization.yaml
  deploy/fullstack/controller/ns.yaml
  deploy/fullstack/kustomization.yaml
  deploy/fullstack/provisioner/kustomization.yaml
  deploy/fullstack/provisioner/ns.yaml
  kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#27 deploy: use `crds` Kustomization from the API repo
  deploy/base/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
