Repository kubernetes-sigs/container-object-storage-interface-controller, pull requests merged in 2021-03, with the labels that each got.

#37 Readme update
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#38 Add deployment documentation
  docs/deployment-guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#42 update api version & glog -> klog
  cmd/controller-manager/controller-manager.go
  go.mod
  go.sum
  pkg/bucketaccessrequest/bucketaccessrequest.go
  pkg/bucketrequest/bucketrequest.go
  pkg/bucketrequest/bucketrequest_test.go
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#41 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#44 added cloudbuild.yaml
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
