Repository kubernetes-sigs/container-object-storage-interface-controller, pull requests merged in 2021-01, with the labels that each got.

#30 Fix the build files so that prow job can run successfully
  Dockerfile
  deploy/base/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#32 Refactor Kustomize templates
  deploy/base/kustomization.yaml
  deploy/fullstack/controller/kustomization.yaml
  deploy/fullstack/controller/ns.yaml
  deploy/fullstack/kustomization.yaml
  deploy/fullstack/provisioner/kustomization.yaml
  deploy/fullstack/provisioner/ns.yaml
  kustomization.yaml
  resources/deployment.yaml
  resources/rbac.yaml
  resources/sa.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#33 fix race condition while creating buckets
  go.mod
  go.sum
  pkg/bucketrequest/bucketrequest.go
  pkg/bucketrequest/bucketrequest_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#34 fix rbac rules and check for errors getting bucketclass
  pkg/bucketaccessrequest/bucketaccessrequest.go
  pkg/bucketaccessrequest/bucketaccessrequest_test.go
  pkg/bucketrequest/bucketrequest.go
  pkg/util/util.go
  resources/deployment.yaml
  resources/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
