Repository kubernetes-sigs/container-object-storage-interface-controller, pull requests merged in 2022-08, with the labels that each got.

#58 Update code with KEP
  cmd/controller-manager/controller-manager.go
  go.mod
  go.sum
  pkg/bucketaccessrequest/bucketaccessrequest.go
  pkg/bucketaccessrequest/bucketaccessrequest_test.go
  pkg/bucketclaim/bucketclaim.go
  pkg/bucketclaim/bucketclaim_test.go
  pkg/bucketrequest/bucketrequest.go
  pkg/util/const.go
  pkg/util/util.go
Labels: cncf-cla: yes, approved, size/XXL, ok-to-test, lgtm

#60 Fixing the api repo import and updated the rbac rules for CRDs
  go.mod
  go.sum
  resources/rbac.yaml
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm

#59 Added push to Cloudbuild.yaml and swapped out quay.io with gcr repo
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm

#61 Fixing the text in deployment guide
  docs/deployment-guide.md
Labels: cncf-cla: yes, approved, ok-to-test, size/XS, lgtm

#62 Doc changes
  cloudbuild.yaml
  docs/deployment-guide.md
Labels: cncf-cla: yes, approved, ok-to-test, size/XS, lgtm

#63 Create CHANGELOG-0.1.md
  CHANGELOG/CHANGELOG-0.1.md
Labels: cncf-cla: yes, approved, lgtm

#64 Update cloudbuild.yaml
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm
